// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3YIlyZqdDEQac-dpXroK6nOsTLF_pT70',
    appId: '1:628071772829:web:eca75262689c39b0f09a74',
    messagingSenderId: '628071772829',
    projectId: 'esp32test-4f2c1',
    authDomain: 'esp32test-4f2c1.firebaseapp.com',
    databaseURL: 'https://esp32test-4f2c1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32test-4f2c1.appspot.com',
    measurementId: 'G-05RPNC02B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqpT8OwWAjrq8Uk5roE5Donv69uyZVQNk',
    appId: '1:628071772829:android:51cca55a10af9e7bf09a74',
    messagingSenderId: '628071772829',
    projectId: 'esp32test-4f2c1',
    databaseURL: 'https://esp32test-4f2c1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32test-4f2c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDBrNSWN1E0VBAZLcdhq_GA3yQPMLLDbM',
    appId: '1:628071772829:ios:f332711465b4c2c9f09a74',
    messagingSenderId: '628071772829',
    projectId: 'esp32test-4f2c1',
    databaseURL: 'https://esp32test-4f2c1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32test-4f2c1.appspot.com',
    iosClientId: '628071772829-m029t3muk1ab9d13qllo34k0g2dq9c0o.apps.googleusercontent.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDBrNSWN1E0VBAZLcdhq_GA3yQPMLLDbM',
    appId: '1:628071772829:ios:f332711465b4c2c9f09a74',
    messagingSenderId: '628071772829',
    projectId: 'esp32test-4f2c1',
    databaseURL: 'https://esp32test-4f2c1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32test-4f2c1.appspot.com',
    iosClientId: '628071772829-m029t3muk1ab9d13qllo34k0g2dq9c0o.apps.googleusercontent.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );
}
